version: '3.1'

services:
  generator:
    image: my-registry:55000/gen:ci-13
    # ports:
    #   - "8080:80"
  mail:
    image: mailhog/mailhog
    # ports:
    #   - "8025:8025"
  integration:
    build: .
    image: my-registry:55000/gen:integration-13
